### ISSUE TITLE
Chunk border rendering crashes the game

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/CoreRendering#10] opened 2020-05-30 18:21 UTC
When in Debug mode <key>F3</key> and pressing <key>F8</key> the game should render the chunk borders in a wire frame. 

This crashes the game with the following error:

```
java.lang.NoClassDefFoundError: org/terasology/rendering/AABBRenderer
    at org.terasology.corerendering.rendering.dag.nodes.OpaqueBlocksNode.renderChunkBoundingBox(OpaqueBlocksNode.java:234)
    at org.terasology.corerendering.rendering.dag.nodes.OpaqueBlocksNode.process(OpaqueBlocksNode.java:210)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
    at org.terasology.rendering.world.WorldRendererImpl.render(WorldRendererImpl.java:370)
    at org.terasology.engine.modes.StateIngame.render(StateIngame.java:206)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:166)
    at org.terasology.engine.TerasologyEngine.tick(TerasologyEngine.java:473)
    at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:427)
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:403)
    at org.terasology.engine.Terasology.main(Terasology.java:163)

```

**Comment by skaldarnar** [comment] 2020-06-06 13:41
This also affects other rendered bounding boxes, like the ones drawn by Structure Templates. It looks like the outlines are drawn to the background instead of augmenting the world around the player.

![image](https://user-images.githubusercontent.com/1448874/83945606-214d2800-a80c-11ea-80d5-52d3faa34e67.png)

**Comment by kBlaszczyk** [comment] 2020-06-08 19:56
I think that the class `AABBRenderer` would need to be annotated with @API to be available to modules at runtime. Unfortunately that doesn't solve the problem...
Does the engine maybe not process the annotations for this particular class for some reason?

**Comment by Cervator** [comment] 2020-06-11 04:40
Closing as fixed by https://github.com/MovingBlocks/Terasology/pull/4042, confirmed locally - thanks @kBlaszczyk ! :-)

**Closed by Cervator** 2020-06-11 04:40 UTC
Labels: bug

**Comment by skaldarnar** [comment] 2020-06-11 09:35
Does that also fix the preview rendering of structure templates? If nobody beats me to it, I'll check that later today...

**Comment by kBlaszczyk** [comment] 2020-06-11 12:03
That's most likely unrelated. It looks like a rendering order issue. Maybe the environment is rendered after the bounding boxes, with a cleared depth buffer. So you can only see the bounding boxes where nothing else was drawn over them.
Deserves it's own issue I think.

**Comment by Cervator** [comment] 2020-06-11 13:55
I think that's been a separate issue for a while yeah :-)
